[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt",
    "src/**",
    "railway.toml",
    "Dockerfile"
]

[env]
DJANGO_SETTINGS_MODULE = "backend.settings"
REDIS_URL = "${{ REDIS_URL }}"  # This will be set by Railway automatically
